E(EPERM,        "Operation not permitted")
E(ENOENT,       "No such file or directory")
E(ESRCH,        "No such process")
E(EINTR,        "Interrupted system call")
E(EIO,          "I/O error")
E(EREMOTEIO,    "Remote I/O error")
E(ENXIO,        "No such device or address")
E(E2BIG,        "Argument list too long")
E(ENOEXEC,      "Exec format error")
E(EBADF,        "Bad file descriptor")
E(EBADFD,       "File descriptor in bad state")
E(ECHILD,       "No child process")
E(EAGAIN,       "Resource temporarily unavailable")
E(ENOMEM,       "Out of memory")
E(EACCES,       "Permission denied")
E(EFAULT,       "Bad address")
E(ENOTBLK,      "Block device required")
E(EBUSY,        "Resource busy")
E(EEXIST,       "File exists")
E(EXDEV,        "Cross-device link")
E(ENODEV,       "No such device")
E(ENOTDIR,      "Not a directory")
E(EISDIR,       "Is a directory")
E(EINVAL,       "Invalid argument")
E(ENFILE,       "Too many open files in system")
E(EMFILE,       "No file descriptors available")
E(ENOTTY,       "Not a tty")
E(ETXTBSY,      "Text file busy")
E(EFBIG,        "File too large")
E(ENOSPC,       "No space left on device")
E(ESPIPE,       "Invalid seek")
E(EROFS,        "Read-only file system")
E(EMLINK,       "Too many links")
E(EPIPE,        "Broken pipe")
E(EDOM,         "Domain error")
E(ERANGE,       "Result not representable")
E(EDEADLK,      "Resource deadlock would occur")
E(ENAMETOOLONG, "Filename too long")
E(ENOLCK,       "No locks available")
E(ENOSYS,       "Function not implemented")
E(ENOTEMPTY,    "Directory not empty")
E(ELOOP,        "Symbolic link loop")
E(ENOMSG,       "No message of desired type")
E(EIDRM,        "Identifier removed")
E(ENOSTR,       "Device not a stream")
E(ENODATA,      "No data available")
E(ETIMEDOUT,    "Operation timed out")
E(ETIME,        "Device timeout")
E(ENOSR,        "Out of streams resources")
E(EREMOTEIO,    "Remote I/O error")
E(ENOLINK,      "Link has been severed")
E(EPROTO,       "Protocol error")
E(EPROTOTYPE,   "Protocol wrong type for socket")
E(EPROTONOSUPPORT,"Protocol not supported")
E(EMULTIHOP,    "Multihop attempted")
E(EBADMSG,      "Bad message")
E(EOVERFLOW,    "Value too large for data type")
E(EBADFD,       "File descriptor in bad state")
E(EILSEQ,       "Illegal byte sequence")
E(ENOTSOCK,     "Not a socket")
E(EDESTADDRREQ, "Destination address required")
E(EMSGSIZE,     "Message too large")
E(EPROTOTYPE,   "Protocol wrong type for socket")
E(ENOPROTOOPT,  "Protocol not available")
E(EPROTONOSUPPORT,"Protocol not supported")
E(ESOCKTNOSUPPORT,"Socket type not supported")
E(ENOTSUP,      "Not supported")
E(EPFNOSUPPORT, "Protocol family not supported")
E(EAFNOSUPPORT, "Address family not supported by protocol")
E(EADDRINUSE,   "Address in use")
E(EADDRNOTAVAIL,"Address not available")
E(ENETDOWN,     "Network is down")
E(ENETUNREACH,  "Network unreachable")
E(ENETRESET,    "Connection reset by network")
E(ECONNABORTED, "Connection aborted")
E(ECONNRESET,   "Connection reset by peer")
E(ENOBUFS,      "No buffer space available")
E(EISCONN,      "Socket is connected")
E(ENOTCONN,     "Socket not connected")
E(ESHUTDOWN,    "Cannot send after socket shutdown")
E(ETIMEDOUT,    "Operation timed out")
E(ECONNREFUSED, "Connection refused")
E(EHOSTDOWN,    "Host is down")
E(EHOSTUNREACH, "Host is unreachable")
E(EALREADY,     "Operation already in progress")
E(EINPROGRESS,  "Operation in progress")
E(ESTALE,       "Stale file handle")
E(EREMOTEIO,    "Remote I/O error")
E(EDQUOT,       "Quota exceeded")
E(ENOMEDIUM,    "No medium found")
E(EMEDIUMTYPE,  "Wrong medium type")
E(ECANCELED,    "Operation canceled")
E(ENOKEY,       "Required key not available")
E(EKEYEXPIRED,  "Key has expired")
E(EKEYREVOKED,  "Key has been revoked")
E(EKEYREJECTED, "Key was rejected by service")
E(EOWNERDEAD,   "Previous owner died")
E(ENOTRECOVERABLE, "State not recoverable")
